name: Contract Development

on:
   push:
    branches:
      - main

jobs:
 test_project:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macOS
            os: macOS-latest
          # - build: Windows
           # os: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Install Sui Move
        run: cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui
      - name: Test Project
        run: sui move test
      - name: Build Project
        run: sui move build
