name: Contract Development

on:
   push:
    branches:
      - master

jobs:
 test_project:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macOS
            os: macOS-latest
          # - build: Windows
           # os: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Install Sui Move
        run: cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet
      - name: Test Project
        run: sui move test
      - name: Build Project
        run: sui move build
